version: '3.7'

services:
  db:
    restart: unless-stopped
    image: mariadb:10
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  wp:
    restart: unless-stopped
    depends_on:
      - db
    image: wordpress:5
    volumes:
      - wp-data:/var/www/html
      #wpconfig#- ./wp/wp-config.php:/var/www/html/wp-config.php
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}

  nginx:
    restart: unless-stopped
    image: nginx
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - certbot-www:/var/www/certbot:ro
      - certbot-certs:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    profiles:
      - certbot
    volumes:
      - certbot-www:/var/www/certbot:rw
      - certbot-certs:/etc/letsencrypt:rw

volumes:
  db-data:
    name: ${COMPOSE_PROJECT_NAME}_db-data
    #externalvols#external: true
  wp-data:
    name: ${COMPOSE_PROJECT_NAME}_wp-data
    #externalvols#external: true
  certbot-www:
    name: ${COMPOSE_PROJECT_NAME}_certbot-www
    #externalvols#external: true
  certbot-certs:
    name: ${COMPOSE_PROJECT_NAME}_certbot-certs
    #externalvols#external: true
