version: '3.7'

services:
  db:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  wp:
    depends_on:
      - db
    image: wordpress:5
    volumes:
      - wp_data:/var/www/html
      #wpconfig#- ./wp/wp-config.php:/var/www/html/wp-config.php
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - certbot-www:/var/www/certbot:ro
      - certbot-certs:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    profiles:
      - certbot
    volumes:
      - certbot-www:/var/www/certbot:rw
      - certbot-certs:/etc/letsencrypt:rw

volumes:
  db_data:
  wp_data:
  certbot-www:
  certbot-certs:
